In [ ]:
print("Hello")

Hello

In [ ]:
import pandas as  pd
import requests

## WEBSCRAPPING MARVEL DATABASE

In [ ]:
url_marvel = "https://en.wikipedia.org/wiki/List_of_Marvel_Cinematic_Universe_films"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}


response = requests.get(url_marvel, headers=headers)

tables = pd.read_html(response.text)

mcu_movies = tables[0]

print(f"Total tables found: {len(tables)}")

# Loop through tables to see which one has the columns you want
for i, table in enumerate(tables):
    print(f"\nTable {i} columns:\n", table.columns)

/tmp/ipython-input-1573713336.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

Total tables found: 41

Table 0 columns:
 Index(['Marvel Cinematic Universe films', 'Marvel Cinematic Universe films.1'], dtype='object')

Table 1 columns:
 Index(['Marvel Cinematic Universe Phases', 'Marvel Cinematic Universe Phases.1'], dtype='object')

Table 2 columns:
 Index(['Film[36]', 'U.S. release date', 'Director', 'Screenwriter(s)',
       'Producer(s)'],
      dtype='object')

Table 3 columns:
 Index(['Film[36]', 'U.S. release date', 'Director(s)', 'Screenwriter(s)',
       'Producer'],
      dtype='object')

Table 4 columns:
 Index(['Film[36]', 'U.S. release date', 'Director(s)', 'Screenwriter(s)',
       'Producer(s)'],
      dtype='object')

Table 5 columns:
 Index(['Film[36]', 'U.S. release date', 'Director', 'Screenwriter(s)',
       'Producer(s)'],
      dtype='object')

Table 6 columns:
 Index(['Film[36][96]', 'U.S. release date', 'Director', 'Screenwriter(s)',
       'Producer(s)'],
      dtype='object')

Table 7 columns:
 Index(['Film[36]', 'U.S. release date', 'Director(s)', 'Screenwriters',
       'Producer(s)', 'Status'],
      dtype='object')

Table 8 columns:
 Index(['Film', 'U.S. release date', 'Director', 'Screenwriter', 'Producer(s)',
       'Status'],
      dtype='object')

Table 9 columns:
 Index(['Character', 'Phase One', 'Phase Two', 'Phase Three', 'Phase Four',
       'Phase Five', 'Phase Six', 'Unnamed: 7'],
      dtype='object')

Table 10 columns:
 MultiIndex([(             'Film',              'Film', 'Phase One'),
            ('U.S. release date', 'U.S. release date', 'Phase One'),
            ( 'Box office gross',   'U.S. and Canada', 'Phase One'),
            ( 'Box office gross', 'Other territories', 'Phase One'),
            ( 'Box office gross',         'Worldwide', 'Phase One'),
            ( 'All-time ranking',   'U.S. and Canada', 'Phase One'),
            ( 'All-time ranking',         'Worldwide', 'Phase One'),
            (           'Budget',            'Budget', 'Phase One'),
            (             'Ref.',              'Ref.', 'Phase One')],
           )

Table 11 columns:
 MultiIndex([(    'Film',            'Film', 'Phase One'),
            ('Critical', 'Rotten Tomatoes', 'Phase One'),
            ('Critical',      'Metacritic', 'Phase One'),
            (  'Public',     'CinemaScore', 'Phase One'),
            (  'Public',        'PostTrak', 'Phase One')],
           )

Table 12 columns:
 Index(['vteMarvel Cinematic Universe', 'vteMarvel Cinematic Universe.1'], dtype='object')

Table 13 columns:
 Index(['Marvel Studios', 'Marvel Studios.1'], dtype='object')

Table 14 columns:
 Index([0, 1], dtype='int64')

Table 15 columns:
 Index([0, 1], dtype='int64')

Table 16 columns:
 Index([0, 1], dtype='int64')

Table 17 columns:
 Index([0, 1], dtype='int64')

Table 18 columns:
 Index([0, 1], dtype='int64')

Table 19 columns:
 Index([0, 1], dtype='int64')

Table 20 columns:
 Index(['Marvel Television', 'Marvel Television.1'], dtype='object')

Table 21 columns:
 Index([0, 1], dtype='int64')

Table 22 columns:
 Index(['Other media', 'Other media.1'], dtype='object')

Table 23 columns:
 Index([0, 1], dtype='int64')

Table 24 columns:
 Index([0, 1], dtype='int64')

Table 25 columns:
 Index(['Cast and characters', 'Cast and characters.1'], dtype='object')

Table 26 columns:
 Index([0, 1], dtype='int64')

Table 27 columns:
 Index([0, 1], dtype='int64')

Table 28 columns:
 Index([0, 1], dtype='int64')

Table 29 columns:
 Index(['Features', 'Features.1'], dtype='object')

Table 30 columns:
 Index(['Music', 'Music.1'], dtype='object')

Table 31 columns:
 Index([0, 1], dtype='int64')

Table 32 columns:
 Index([0, 1], dtype='int64')

Table 33 columns:
 Index(['Inspired media', 'Inspired media.1'], dtype='object')

Table 34 columns:
 Index([0, 1], dtype='int64')

Table 35 columns:
 Index(['vteLive-action theatrical films based on Marvel Comics', 'vteLive-action theatrical films based on Marvel Comics.1'], dtype='object')

Table 36 columns:
 Index([0, 1], dtype='int64')

Table 37 columns:
 Index([0, 1], dtype='int64')

Table 38 columns:
 Index(['vteWalt Disney Studios films', 'vteWalt Disney Studios films.1'], dtype='object')

Table 39 columns:
 Index([0, 1], dtype='int64')

Table 40 columns:
 Index([0, 1], dtype='int64')

## Extracting needed tables

In [ ]:
mcu_table = tables[10]  # Table with Box office and Budget
ratings_table = tables[11]  # Table with critic/public ratings

print(ratings_table)

                                           Film                Critical  \
                                           Film         Rotten Tomatoes
                                      Phase One               Phase One
0                                      Iron Man  94% (282 reviews)[329]
1                           The Incredible Hulk  68% (237 reviews)[332]
2                                    Iron Man 2  72% (305 reviews)[335]
3                                          Thor  77% (296 reviews)[338]
4            Captain America: The First Avenger  80% (276 reviews)[341]
5                                  The Avengers  91% (368 reviews)[344]
6                                     Phase Two               Phase Two
7                                    Iron Man 3  79% (331 reviews)[347]
8                          Thor: The Dark World  67% (290 reviews)[350]
9           Captain America: The Winter Soldier  90% (311 reviews)[352]
10                      Guardians of the Galaxy  92% (336 reviews)[355]
11                      Avengers: Age of Ultron  75% (372 reviews)[359]
12                                      Ant-Man  83% (341 reviews)[361]
13                                  Phase Three             Phase Three
14                   Captain America: Civil War  90% (431 reviews)[364]
15                               Doctor Strange  89% (389 reviews)[366]
16               Guardians of the Galaxy Vol. 2  85% (425 reviews)[369]
17                       Spider-Man: Homecoming  92% (400 reviews)[371]
18                               Thor: Ragnarok  93% (439 reviews)[374]
19                                Black Panther  96% (532 reviews)[376]
20                       Avengers: Infinity War  85% (492 reviews)[379]
21                         Ant-Man and the Wasp  87% (446 reviews)[383]
22                               Captain Marvel  79% (552 reviews)[385]
23                            Avengers: Endgame  94% (551 reviews)[388]
24                    Spider-Man: Far From Home  91% (455 reviews)[391]
25                                   Phase Four              Phase Four
26                                  Black Widow  79% (462 reviews)[394]
27    Shang-Chi and the Legend of the Ten Rings  92% (343 reviews)[397]
28                                     Eternals  47% (417 reviews)[400]
29                      Spider-Man: No Way Home  93% (432 reviews)[403]
30  Doctor Strange in the Multiverse of Madness  73% (466 reviews)[406]
31                       Thor: Love and Thunder  63% (449 reviews)[409]
32               Black Panther: Wakanda Forever  84% (450 reviews)[412]
33                                   Phase Five              Phase Five
34            Ant-Man and the Wasp: Quantumania  46% (412 reviews)[415]
35               Guardians of the Galaxy Vol. 3  82% (407 reviews)[418]
36                                  The Marvels  62% (370 reviews)[421]
37                         Deadpool & Wolverine  78% (413 reviews)[424]
38             Captain America: Brave New World  46% (365 reviews)[427]
39                                Thunderbolts*  88% (354 reviews)[430]
40                                    Phase Six               Phase Six
41              The Fantastic Four: First Steps  87% (388 reviews)[433]

                               Public
              Metacritic  CinemaScore     PostTrak
               Phase One    Phase One    Phase One
0   79 (38 reviews)[330]       A[331]            —
1   61 (38 reviews)[333]      A−[334]            —
2   57 (40 reviews)[336]       A[337]            —
3   57 (40 reviews)[339]      B+[340]            —
4   66 (43 reviews)[342]      A−[343]            —
5   69 (43 reviews)[345]      A+[346]            —
6              Phase Two    Phase Two    Phase Two
7   62 (44 reviews)[348]       A[349]            —
8   54 (44 reviews)[351]      A−[340]            —
9   70 (48 reviews)[353]       A[354]            —
10  76 (53 reviews)[356]       A[357]     90%[358]
11  66 (49 reviews)[360]       A[346]     90%[346]
12  64 (44 reviews)[362]       A[363]            —
13           Phase Three  Phase Three  Phase Three
14  75 (53 reviews)[365]       A[346]     88%[346]
15  72 (49 reviews)[367]       A[368]     91%[368]
16  67 (48 reviews)[370]       A[358]     93%[358]
17  73 (51 reviews)[372]       A[373]     89%[373]
18  74 (51 reviews)[375]       A[340]     90%[340]
19  88 (55 reviews)[377]      A+[378]     95%[378]
20  68 (54 reviews)[380]       A[381]     87%[382]
21  70 (56 reviews)[384]      A−[290]            —
22  64 (56 reviews)[386]       A[387]            —
23  78 (57 reviews)[389]      A+[390]            —
24  69 (55 reviews)[392]       A[393]            —
25            Phase Four   Phase Four   Phase Four
26  68 (58 reviews)[395]      A−[396]     88%[396]
27  71 (52 reviews)[398]       A[399]     91%[399]
28  52 (62 reviews)[401]       B[402]     78%[402]
29  71 (60 reviews)[404]      A+[405]     96%[405]
30  60 (65 reviews)[407]      B+[408]     82%[408]
31  57 (64 reviews)[410]      B+[411]     77%[411]
32  67 (62 reviews)[413]       A[414]     93%[414]
33            Phase Five   Phase Five   Phase Five
34  48 (61 reviews)[416]       B[417]     75%[417]
35  64 (63 reviews)[419]       A[420]     91%[420]
36  50 (57 reviews)[422]       B[423]     73%[423]
37  56 (58 reviews)[425]       A[426]     96%[426]
38  42 (56 reviews)[428]      B–[429]            —
39  68 (52 reviews)[431]      A–[432]            —
40             Phase Six    Phase Six    Phase Six
41  65 (54 reviews)[434]      A-[435]     86%[436]

In [ ]:
# Flatten MultiIndex columns MCU TABLE
mcu_table.columns = [' '.join(col).strip() if type(col) is tuple else col for col in mcu_table.columns]
print(mcu_table.head())

                  Film Film Phase One  \
0                            Iron Man
1                 The Incredible Hulk
2                          Iron Man 2
3                                Thor
4  Captain America: The First Avenger

  U.S. release date U.S. release date Phase One  \
0                                   May 2, 2008
1                                 June 13, 2008
2                                   May 7, 2010
3                                   May 6, 2011
4                                 July 22, 2011

  Box office gross U.S. and Canada Phase One  \
0                               $319,034,126
1                               $134,806,913
2                               $312,433,331
3                               $181,030,624
4                               $176,654,505

  Box office gross Other territories Phase One  \
0                                 $266,762,121
1                                 $129,964,083
2                                 $311,500,000
3                                 $268,295,994
4                                 $193,915,269

  Box office gross Worldwide Phase One  \
0                         $585,796,247
1                         $264,770,996
2                         $623,933,331
3                         $449,326,618
4                         $370,569,774

  All-time ranking U.S. and Canada Phase One  \
0                                         89
1                                        494
2                                         95
3                                        280
4                                        298

  All-time ranking Worldwide Phase One Budget Budget Phase One  \
0                                  190            $140 million
1                                  625      $137.5–150 million
2                                  172        $170–200 million
3                                  290            $150 million
4                                  394            $140 million

  Ref. Ref. Phase One
0               [258]
1          [259][260]
2          [261][262]
3               [263]
4               [264]

In [ ]:
ratings_table.columns = [' '.join(col).strip() if type(col) is tuple else col for col in ratings_table.columns] # Ratings tables
print(ratings_table.head())

                  Film Film Phase One Critical Rotten Tomatoes Phase One  \
0                            Iron Man             94% (282 reviews)[329]
1                 The Incredible Hulk             68% (237 reviews)[332]
2                          Iron Man 2             72% (305 reviews)[335]
3                                Thor             77% (296 reviews)[338]
4  Captain America: The First Avenger             80% (276 reviews)[341]

  Critical Metacritic Phase One Public CinemaScore Phase One  \
0          79 (38 reviews)[330]                       A[331]
1          61 (38 reviews)[333]                      A−[334]
2          57 (40 reviews)[336]                       A[337]
3          57 (40 reviews)[339]                      B+[340]
4          66 (43 reviews)[342]                      A−[343]

  Public PostTrak Phase One
0                         —
1                         —
2                         —
3                         —
4                         —

CHNAGING NAMES OF THE COLUMNS

In [ ]:
mcu_table = mcu_table.rename(columns={
    'Film Film Phase One': 'Movie',
    'U.S. release date U.S. release date Phase One': 'Release_Date',
    'Box office gross Worldwide Phase One': 'Box_Office',
    'Budget Budget Phase One': 'Budget',
    'All-time ranking Worldwide Phase One': 'World_Rankings',
    'Budget Budget Phase On': 'Budget'
})

print(mcu_table.head())

                                Movie   Release_Date  \
0                            Iron Man    May 2, 2008
1                 The Incredible Hulk  June 13, 2008
2                          Iron Man 2    May 7, 2010
3                                Thor    May 6, 2011
4  Captain America: The First Avenger  July 22, 2011

  Box office gross U.S. and Canada Phase One  \
0                               $319,034,126
1                               $134,806,913
2                               $312,433,331
3                               $181,030,624
4                               $176,654,505

  Box office gross Other territories Phase One    Box_Office  \
0                                 $266,762,121  $585,796,247
1                                 $129,964,083  $264,770,996
2                                 $311,500,000  $623,933,331
3                                 $268,295,994  $449,326,618
4                                 $193,915,269  $370,569,774

  All-time ranking U.S. and Canada Phase One World_Rankings  \
0                                         89            190
1                                        494            625
2                                         95            172
3                                        280            290
4                                        298            394

               Budget Ref. Ref. Phase One
0        $140 million               [258]
1  $137.5–150 million          [259][260]
2    $170–200 million          [261][262]
3        $150 million               [263]
4        $140 million               [264]

With Ratings table

In [ ]:
ratings_table1 = ratings_table.rename(columns={
    'Film Film Phase One': 'Movie',
    'Critical Rotten Tomatoes Phase One': 'Rotten_Tomatoes',
})

Ratings_clean = ratings_table1[['Movie', 'Rotten_Tomatoes']]

print(Ratings_clean.head())

                                Movie         Rotten_Tomatoes
0                            Iron Man  94% (282 reviews)[329]
1                 The Incredible Hulk  68% (237 reviews)[332]
2                          Iron Man 2  72% (305 reviews)[335]
3                                Thor  77% (296 reviews)[338]
4  Captain America: The First Avenger  80% (276 reviews)[341]

## SELECTING RELEVANT COLUMNS

In [ ]:
mcu_clean = mcu_table[['Movie', 'Release_Date', 'Budget', 'Box_Office']]
mcu_clean['Franchise'] = 'Marvel'
print(mcu_clean.head())

                                Movie   Release_Date              Budget  \
0                            Iron Man    May 2, 2008        $140 million
1                 The Incredible Hulk  June 13, 2008  $137.5–150 million
2                          Iron Man 2    May 7, 2010    $170–200 million
3                                Thor    May 6, 2011        $150 million
4  Captain America: The First Avenger  July 22, 2011        $140 million

     Box_Office Franchise
0  $585,796,247    Marvel
1  $264,770,996    Marvel
2  $623,933,331    Marvel
3  $449,326,618    Marvel
4  $370,569,774    Marvel

/tmp/ipython-input-1306693908.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mcu_clean['Franchise'] = 'Marvel'

Merging two tables of MCU franchise

In [ ]:
M_Clean = M_Clean = pd.merge(
    mcu_clean,         # main table
    Ratings_clean,     # ratings table
    on="Movie",         # common column
    how="left"         # keep all films, add ratings where available
)

M_Clean = M_Clean.drop(M_Clean.index[-1]) # dropping last row as it is total
print(M_Clean.head(50))

                                          Movie       Release_Date  \
0                                      Iron Man        May 2, 2008
1                           The Incredible Hulk      June 13, 2008
2                                    Iron Man 2        May 7, 2010
3                                          Thor        May 6, 2011
4            Captain America: The First Avenger      July 22, 2011
5                                  The Avengers        May 4, 2012
6                                     Phase Two          Phase Two
7                                    Iron Man 3        May 3, 2013
8                          Thor: The Dark World   November 8, 2013
9           Captain America: The Winter Soldier      April 4, 2014
10                      Guardians of the Galaxy     August 1, 2014
11                      Avengers: Age of Ultron        May 1, 2015
12                                      Ant-Man      July 17, 2015
13                                  Phase Three        Phase Three
14                   Captain America: Civil War        May 6, 2016
15                               Doctor Strange   November 4, 2016
16               Guardians of the Galaxy Vol. 2        May 5, 2017
17                       Spider-Man: Homecoming       July 7, 2017
18                               Thor: Ragnarok   November 3, 2017
19                                Black Panther  February 16, 2018
20                       Avengers: Infinity War     April 27, 2018
21                         Ant-Man and the Wasp       July 6, 2018
22                               Captain Marvel      March 8, 2019
23                            Avengers: Endgame     April 26, 2019
24                    Spider-Man: Far From Home       July 2, 2019
25                                   Phase Four         Phase Four
26                                  Black Widow       July 9, 2021
27    Shang-Chi and the Legend of the Ten Rings  September 3, 2021
28                                     Eternals   November 5, 2021
29                      Spider-Man: No Way Home  December 17, 2021
30  Doctor Strange in the Multiverse of Madness        May 6, 2022
31                       Thor: Love and Thunder       July 8, 2022
32               Black Panther: Wakanda Forever  November 11, 2022
33                                   Phase Five         Phase Five
34            Ant-Man and the Wasp: Quantumania  February 17, 2023
35               Guardians of the Galaxy Vol. 3        May 5, 2023
36                                  The Marvels  November 10, 2023
37                         Deadpool & Wolverine      July 26, 2024
38             Captain America: Brave New World  February 14, 2025
39                                Thunderbolts*        May 2, 2025
40                                    Phase Six          Phase Six
41              The Fantastic Four: First Steps      July 25, 2025

                Budget       Box_Office Franchise         Rotten_Tomatoes
0         $140 million     $585,796,247    Marvel  94% (282 reviews)[329]
1   $137.5–150 million     $264,770,996    Marvel  68% (237 reviews)[332]
2     $170–200 million     $623,933,331    Marvel  72% (305 reviews)[335]
3         $150 million     $449,326,618    Marvel  77% (296 reviews)[338]
4         $140 million     $370,569,774    Marvel  80% (276 reviews)[341]
5         $220 million   $1,520,538,536    Marvel  91% (368 reviews)[344]
6            Phase Two        Phase Two    Marvel               Phase Two
7         $200 million   $1,215,577,205    Marvel  79% (331 reviews)[347]
8     $150–170 million     $644,783,140    Marvel  67% (290 reviews)[350]
9     $170–177 million     $714,421,503    Marvel  90% (311 reviews)[352]
10        $170 million     $773,350,147    Marvel  92% (336 reviews)[355]
11    $250–444 million   $1,405,018,048    Marvel  75% (372 reviews)[359]
12        $130 million     $519,311,965    Marvel  83% (341 reviews)[361]
13         Phase Three      Phase Three    Marvel             Phase Three
14        $250 million   $1,155,046,416    Marvel  90% (431 reviews)[364]
15        $165 million     $677,796,076    Marvel  89% (389 reviews)[366]
16        $200 million     $863,756,051    Marvel  85% (425 reviews)[369]
17        $175 million     $880,166,924    Marvel  92% (400 reviews)[371]
18        $180 million     $855,301,806    Marvel  93% (439 reviews)[374]
19        $200 million   $1,374,959,729    Marvel  96% (532 reviews)[376]
20    $325–400 million   $2,052,415,039    Marvel  85% (492 reviews)[379]
21        $162 million     $622,674,139    Marvel  87% (446 reviews)[383]
22    $150–175 million   $1,131,416,446    Marvel  79% (552 reviews)[385]
23    $356–400 million   $2,799,439,100    Marvel  94% (551 reviews)[388]
24        $160 million   $1,138,121,790    Marvel  91% (455 reviews)[391]
25          Phase Four       Phase Four    Marvel              Phase Four
26        $200 million  $379,751,655[e]    Marvel  79% (462 reviews)[394]
27    $150–200 million     $432,243,292    Marvel  92% (343 reviews)[397]
28      $236.2 million     $402,064,899    Marvel  47% (417 reviews)[400]
29        $200 million   $1,928,040,905    Marvel  93% (432 reviews)[403]
30    $172–200 million     $955,775,804    Marvel  73% (466 reviews)[406]
31        $250 million     $760,928,081    Marvel  63% (449 reviews)[409]
32        $250 million     $859,208,836    Marvel  84% (450 reviews)[412]
33          Phase Five       Phase Five    Marvel              Phase Five
34      $388.4 million     $476,071,180    Marvel  46% (412 reviews)[415]
35        $250 million     $845,555,777    Marvel  82% (407 reviews)[418]
36        $375 million     $206,136,825    Marvel  62% (370 reviews)[421]
37        $200 million   $1,338,073,645    Marvel  78% (413 reviews)[424]
38        $180 million     $415,101,577    Marvel  46% (365 reviews)[427]
39        $180 million     $382,436,917    Marvel  88% (354 reviews)[430]
40           Phase Six        Phase Six    Marvel               Phase Six
41        $200 million     $511,526,150    Marvel  87% (388 reviews)[433]

In [ ]:
M_Clean = M_Clean[~M_Clean['Movie'].str.contains('Phase', na=False)]



M_Clean = M_Clean.reset_index(drop=True)

M_Clean.index = M_Clean.index + 1



M_Clean

,Movie,Release_Date,Budget,Box_Office,Franchise,Rotten_Tomatoes
1,Iron Man,"May 2, 2008",$140 million,"$585,796,247",Marvel,94% (282 reviews)[329]
2,The Incredible Hulk,"June 13, 2008",$137.5–150 million,"$264,770,996",Marvel,68% (237 reviews)[332]
3,Iron Man 2,"May 7, 2010",$170–200 million,"$623,933,331",Marvel,72% (305 reviews)[335]
4,Thor,"May 6, 2011",$150 million,"$449,326,618",Marvel,77% (296 reviews)[338]
5,Captain America: The First Avenger,"July 22, 2011",$140 million,"$370,569,774",Marvel,80% (276 reviews)[341]
6,The Avengers,"May 4, 2012",$220 million,"$1,520,538,536",Marvel,91% (368 reviews)[344]
7,Iron Man 3,"May 3, 2013",$200 million,"$1,215,577,205",Marvel,79% (331 reviews)[347]
8,Thor: The Dark World,"November 8, 2013",$150–170 million,"$644,783,140",Marvel,67% (290 reviews)[350]
9,Captain America: The Winter Soldier,"April 4, 2014",$170–177 million,"$714,421,503",Marvel,90% (311 reviews)[352]
10,Guardians of the Galaxy,"August 1, 2014",$170 million,"$773,350,147",Marvel,92% (336 reviews)[355]
11,Avengers: Age of Ultron,"May 1, 2015",$250–444 million,"$1,405,018,048",Marvel,75% (372 reviews)[359]
12,Ant-Man,"July 17, 2015",$130 million,"$519,311,965",Marvel,83% (341 reviews)[361]
13,Captain America: Civil War,"May 6, 2016",$250 million,"$1,155,046,416",Marvel,90% (431 reviews)[364]
14,Doctor Strange,"November 4, 2016",$165 million,"$677,796,076",Marvel,89% (389 reviews)[366]
15,Guardians of the Galaxy Vol. 2,"May 5, 2017",$200 million,"$863,756,051",Marvel,85% (425 reviews)[369]
16,Spider-Man: Homecoming,"July 7, 2017",$175 million,"$880,166,924",Marvel,92% (400 reviews)[371]
17,Thor: Ragnarok,"November 3, 2017",$180 million,"$855,301,806",Marvel,93% (439 reviews)[374]
18,Black Panther,"February 16, 2018",$200 million,"$1,374,959,729",Marvel,96% (532 reviews)[376]
19,Avengers: Infinity War,"April 27, 2018",$325–400 million,"$2,052,415,039",Marvel,85% (492 reviews)[379]
20,Ant-Man and the Wasp,"July 6, 2018",$162 million,"$622,674,139",Marvel,87% (446 reviews)[383]
21,Captain Marvel,"March 8, 2019",$150–175 million,"$1,131,416,446",Marvel,79% (552 reviews)[385]
22,Avengers: Endgame,"April 26, 2019",$356–400 million,"$2,799,439,100",Marvel,94% (551 reviews)[388]
23,Spider-Man: Far From Home,"July 2, 2019",$160 million,"$1,138,121,790",Marvel,91% (455 reviews)[391]
24,Black Widow,"July 9, 2021",$200 million,"$379,751,655[e]",Marvel,79% (462 reviews)[394]
25,Shang-Chi and the Legend of the Ten Rings,"September 3, 2021",$150–200 million,"$432,243,292",Marvel,92% (343 reviews)[397]
26,Eternals,"November 5, 2021",$236.2 million,"$402,064,899",Marvel,47% (417 reviews)[400]
27,Spider-Man: No Way Home,"December 17, 2021",$200 million,"$1,928,040,905",Marvel,93% (432 reviews)[403]
28,Doctor Strange in the Multiverse of Madness,"May 6, 2022",$172–200 million,"$955,775,804",Marvel,73% (466 reviews)[406]
29,Thor: Love and Thunder,"July 8, 2022",$250 million,"$760,928,081",Marvel,63% (449 reviews)[409]
30,Black Panther: Wakanda Forever,"November 11, 2022",$250 million,"$859,208,836",Marvel,84% (450 reviews)[412]
31,Ant-Man and the Wasp: Quantumania,"February 17, 2023",$388.4 million,"$476,071,180",Marvel,46% (412 reviews)[415]
32,Guardians of the Galaxy Vol. 3,"May 5, 2023",$250 million,"$845,555,777",Marvel,82% (407 reviews)[418]
33,The Marvels,"November 10, 2023",$375 million,"$206,136,825",Marvel,62% (370 reviews)[421]
34,Deadpool & Wolverine,"July 26, 2024",$200 million,"$1,338,073,645",Marvel,78% (413 reviews)[424]
35,Captain America: Brave New World,"February 14, 2025",$180 million,"$415,101,577",Marvel,46% (365 reviews)[427]
36,Thunderbolts*,"May 2, 2025",$180 million,"$382,436,917",Marvel,88% (354 reviews)[430]
37,The Fantastic Four: First Steps,"July 25, 2025",$200 million,"$511,526,150",Marvel,87% (388 reviews)[433]

# WEB SCRAPING FOR DCEU MOVIES

In [ ]:
url_DCEU = "https://en.wikipedia.org/wiki/DC_Extended_Universe"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}


response = requests.get(url_DCEU, headers=headers)

tables1 = pd.read_html(response.text)


print(f"Total tables found: {len(tables1)}")

# Loop through tables to see which one has the columns you want
for i, table2 in enumerate(tables1):
    print(f"\nTable {i} columns:\n", table2.columns)

/tmp/ipython-input-3817745895.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables1 = pd.read_html(response.text)

Total tables found: 34

Table 0 columns:
 Index(['DC Extended Universe', 'DC Extended Universe.1'], dtype='object')

Table 1 columns:
 Index(['Film', 'U.S. release date', 'Director', 'Screenwriter(s)', 'Story by',
       'Producer(s)'],
      dtype='object')

Table 2 columns:
 MultiIndex([(             'Series',         'Series'),
            (             'Season',         'Season'),
            (           'Episodes',       'Episodes'),
            (           'Episodes',     'Episodes.1'),
            ('Originally released', 'First released'),
            ('Originally released',  'Last released'),
            (         'Showrunner',     'Showrunner')],
           )

Table 3 columns:
 MultiIndex([( 'Character',                          'Character'),
            (      'Film',                       'Man of Steel'),
            (      'Film', 'Batman v Superman: Dawn of Justice'),
            (      'Film',                'Suicide Squad films'),
            (      'Film',                 'Wonder Woman films'),
            (      'Film',               'Justice League films'),
            (      'Film',                      'Aquaman films'),
            (      'Film',                       'Shazam films'),
            (      'Film',                      'Birds of Prey'),
            (      'Film',                         'Black Adam'),
            (      'Film',                          'The Flash'),
            ('Television',                         'Peacemaker')],
           )

Table 4 columns:
 MultiIndex([(             'Film',              'Film'),
            ('U.S. release date', 'U.S. release date'),
            ( 'Box office gross',   'U.S. and Canada'),
            ( 'Box office gross', 'Other territories'),
            ( 'Box office gross',         'Worldwide'),
            (           'Budget',            'Budget'),
            (             'Ref.',              'Ref.')],
           )

Table 5 columns:
 MultiIndex([(   'Title',           'Title'),
            ('Critical', 'Rotten Tomatoes'),
            ('Critical',      'Metacritic'),
            (  'Public',     'CinemaScore'),
            (  'Public',        'PostTrak')],
           )

Table 6 columns:
 Index(['Title', 'Season', 'Rotten Tomatoes', 'Metacritic'], dtype='object')

Table 7 columns:
 Index(['Title', 'U.S. release date', 'Performed by', 'Length', 'Label'], dtype='object')

Table 8 columns:
 Index(['Title', 'U.S. release date', 'Length', 'Artist(s)', 'Label', 'Film'], dtype='object')

Table 9 columns:
 Index(['Title', 'U.S. release date', 'Length', 'Artist(s)', 'Label',
       'Television'],
      dtype='object')

Table 10 columns:
 Index(['Title', 'Publication date(s)', 'Writer(s)', 'Note'], dtype='object')

Table 11 columns:
 Index(['Title', 'Issue(s)', 'Publication date(s)', 'Writer(s)', 'Artist(s)',
       'Notes'],
      dtype='object')

Table 12 columns:
 Index(['Title', 'Release date(s)', 'Publisher(s)', 'Notes'], dtype='object')

Table 13 columns:
 Index(['Title', 'Release date', 'Director'], dtype='object')

Table 14 columns:
 Index(['vteDC Extended Universe', 'vteDC Extended Universe.1'], dtype='object')

Table 15 columns:
 Index([0, 1], dtype='int64')

Table 16 columns:
 Index(['vteDC Studios', 'vteDC Studios.1'], dtype='object')

Table 17 columns:
 Index([0, 1], dtype='int64')

Table 18 columns:
 Index(['vteDC Comics Multiverse', 'vteDC Comics Multiverse.1'], dtype='object')

Table 19 columns:
 Index([0, 1], dtype='int64')

Table 20 columns:
 Index([0, 1], dtype='int64')

Table 21 columns:
 Index(['vteJustice League characters', 'vteJustice League characters.1'], dtype='object')

Table 22 columns:
 Index([0, 1], dtype='int64')

Table 23 columns:
 Index([0, 1], dtype='int64')

Table 24 columns:
 Index([0, 1], dtype='int64')

Table 25 columns:
 Index([0, 1], dtype='int64')

Table 26 columns:
 Index([0, 1], dtype='int64')

Table 27 columns:
 Index(['vteWarner Bros. Discovery franchises and series', 'vteWarner Bros. Discovery franchises and series.1'], dtype='object')

Table 28 columns:
 Index([0, 1], dtype='int64')

Table 29 columns:
 Index([0, 1], dtype='int64')

Table 30 columns:
 Index([0, 1], dtype='int64')

Table 31 columns:
 Index(['vteLive-action films based on DC Comics', 'vteLive-action films based on DC Comics.1'], dtype='object')

Table 32 columns:
 Index([0, 1], dtype='int64')

Table 33 columns:
 Index([0, 1], dtype='int64')

In [ ]:
dcu_table = tables1[4]  # Table with Box office and Budget
dratings_table = tables1[5]  # Table with critic/public ratings

dcu_table.columns = [' '.join(col).strip() if type(col) is tuple else col for col in dcu_table.columns]


dratings_table.columns = [' '.join(col).strip() if type(col) is tuple else col for col in dratings_table.columns]

dcu_table = dcu_table.rename(columns={
    'Film Film': 'Movie',
    'U.S. release date U.S. release date': 'Release_Date',
    'Box office gross Worldwide': 'Box_Office',
    'Budget Budget': 'Budget'
})

dratings_table = dratings_table.rename(columns={'Title Title' : 'Movie', 'Critical Rotten Tomatoes' : 'Rotten_Tomatoes'})

dcu_table = dcu_table[['Movie', 'Release_Date', 'Box_Office', 'Budget']]
dcu_table['Franchise'] = 'DC'

dratings_table = dratings_table[['Movie', 'Rotten_Tomatoes']]

D_Clean = pd.merge(
    dcu_table,
    dratings_table,
    on='Movie',
    how='left')

D_Clean = D_Clean.drop(D_Clean.index[-1])
print(D_Clean.tail())
print(D_Clean.shape)

                           Movie       Release_Date    Box_Office  \
10                    Black Adam   October 21, 2022  $393,452,111
11      Shazam! Fury of the Gods     March 17, 2023  $134,138,006
12                     The Flash      June 16, 2023  $271,433,313
13                   Blue Beetle    August 18, 2023  $130,788,072
14  Aquaman and the Lost Kingdom  December 22, 2023  $439,381,226

          Budget Franchise         Rotten_Tomatoes
10  $190 million        DC  39% (307 reviews)[609]
11  $125 million        DC  49% (263 reviews)[612]
12  $200 million        DC  63% (390 reviews)[614]
13  $104 million        DC  77% (277 reviews)[617]
14  $205 million        DC  33% (213 reviews)[620]
(15, 6)

In [ ]:
url_DCU = "https://en.wikipedia.org/wiki/DC_Universe_(franchise)"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}


response = requests.get(url_DCU, headers=headers)

tables2 = pd.read_html(response.text)


print(f"Total tables found: {len(tables2)}")

# Loop through tables to see which one has the columns you want
for i, table3 in enumerate(tables2):
    print(f"\nTable {i} columns:\n", table3.columns)

Total tables found: 25

Table 0 columns:
 Index(['DC Universe', 'DC Universe.1'], dtype='object')

Table 1 columns:
 MultiIndex([(             'Film', ...),
            ('U.S. release date', ...),
            (         'Director', ...),
            (  'Screenwriter(s)', ...),
            (        'Producers', ...),
            (           'Status', ...)],
           )

Table 2 columns:
 MultiIndex([(             'Series',              'Series'),
            (             'Season',              'Season'),
            (           'Episodes',            'Episodes'),
            (           'Episodes',          'Episodes.1'),
            ('Originally released',      'First released'),
            ('Originally released',       'Last released'),
            ('Originally released',             'Network'),
            (      'Showrunner(s)',       'Showrunner(s)'),
            (             'Status',              'Status'),
            ( 'Unnamed: 9_level_0',  'Unnamed: 9_level_1'),
            ('Unnamed: 10_level_0', 'Unnamed: 10_level_1'),
            ('Unnamed: 11_level_0', 'Unnamed: 11_level_1'),
            ('Unnamed: 12_level_0', 'Unnamed: 12_level_1')],
           )

Table 3 columns:
 MultiIndex([(        'Character',                   'Character'),
            (            'Films',                    'Superman'),
            (            'Films',                   'Supergirl'),
            (            'Films',             'Man of Tomorrow'),
            ('Television series', 'Creature Commandos season 1'),
            ('Television series',         'Peacemaker season 2'),
            ('Television series',                    'Lanterns'),
            ('Television series',                      'Waller')],
           )

Table 4 columns:
 MultiIndex([(             'Film',              'Film'),
            ('U.S. release date', 'U.S. release date'),
            ( 'Box office gross',   'U.S. and Canada'),
            ( 'Box office gross', 'Other territories'),
            ( 'Box office gross',         'Worldwide'),
            (           'Budget',            'Budget'),
            (             'Ref.',              'Ref.')],
           )

Table 5 columns:
 MultiIndex([(   'Title',           'Title'),
            ('Critical', 'Rotten Tomatoes'),
            ('Critical',      'Metacritic'),
            (  'Public',     'CinemaScore'),
            (  'Public',        'PostTrak')],
           )

Table 6 columns:
 Index(['Series', 'Season', 'Rotten Tomatoes', 'Metacritic'], dtype='object')

Table 7 columns:
 Index(['Title', 'U.S. release date', 'Performed by', 'Length', 'Label'], dtype='object')

Table 8 columns:
 Index(['vteDC Studios', 'vteDC Studios.1'], dtype='object')

Table 9 columns:
 Index([0, 1], dtype='int64')

Table 10 columns:
 Index(['vteLive-action films based on DC Comics', 'vteLive-action films based on DC Comics.1'], dtype='object')

Table 11 columns:
 Index([0, 1], dtype='int64')

Table 12 columns:
 Index([0, 1], dtype='int64')

Table 13 columns:
 Index(['vteLive-action TV series based on DC Comics publications', 'vteLive-action TV series based on DC Comics publications.1'], dtype='object')

Table 14 columns:
 Index([0, 1], dtype='int64')

Table 15 columns:
 Index(['vteDC Comics', 'vteDC Comics.1', 'vteDC Comics.2'], dtype='object')

Table 16 columns:
 Index([0, 1], dtype='int64')

Table 17 columns:
 Index(['vteWarner Bros. Discovery franchises and series', 'vteWarner Bros. Discovery franchises and series.1'], dtype='object')

Table 18 columns:
 Index([0, 1], dtype='int64')

Table 19 columns:
 Index([0, 1], dtype='int64')

Table 20 columns:
 Index([0, 1], dtype='int64')

Table 21 columns:
 Index(['vteDC Extended Universe', 'vteDC Extended Universe.1'], dtype='object')

Table 22 columns:
 Index([0, 1], dtype='int64')

Table 23 columns:
 Index(['vteJames Gunn', 'vteJames Gunn.1'], dtype='object')

Table 24 columns:
 Index([0, 1], dtype='int64')

/tmp/ipython-input-3882017197.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables2 = pd.read_html(response.text)

In [ ]:
dc_table = tables2[4]  # Table with Box office and Budget
drating_table = tables2[5]  # Table with critic/public ratings

dc_table.columns = [' '.join(col).strip() if type(col) is tuple else col for col in dc_table.columns]


drating_table.columns = [' '.join(col).strip() if type(col) is tuple else col for col in drating_table.columns]

dc_table = dc_table.rename(columns={
    'Film Film': 'Movie',
    'U.S. release date U.S. release date': 'Release_Date',
    'Box office gross Worldwide': 'Box_Office',
    'Budget Budget': 'Budget'
})

drating_table = drating_table.rename(columns={'Title Title' : 'Movie', 'Critical Rotten Tomatoes' : 'Rotten_Tomatoes'})


dc_table = dc_table[['Movie', 'Release_Date', 'Box_Office', 'Budget']]
dc_table['Franchise'] = 'DC'

drating_table = drating_table[['Movie', 'Rotten_Tomatoes']]

dc_table.index = dc_table.index + 1

dc_table = pd.merge(dc_table,
                    drating_table,
                    on='Movie',
                    how='left')
dc_table = dc_table.drop(dc_table.index[-1])
dc_table.index = dc_table.index + 1

print(dc_table)
dc_table.shape

      Movie   Release_Date    Box_Office        Budget Franchise  \
1  Superman  July 11, 2025  $612,263.305  $225 million        DC

          Rotten_Tomatoes
1  83% (484 reviews)[240]

(1, 6)

In [ ]:
DCMovies1  = pd.concat([D_Clean, dc_table], ignore_index=True)
DCMovies1.index = DCMovies1.index + 1



DCMovies1

,Movie,Release_Date,Box_Office,Budget,Franchise,Rotten_Tomatoes
1,Man of Steel,"June 14, 2013","$670,145,518",$225 million,DC,57% (340 reviews)[578]
2,Batman v Superman: Dawn of Justice,"March 25, 2016","$874,362,803",$250 million,DC,29% (439 reviews)[581]
3,Suicide Squad,"August 5, 2016","$749,200,054",$175 million,DC,26% (394 reviews)[584]
4,Wonder Woman,"June 2, 2017","$823,970,682",$149 million,DC,93% (480 reviews)[587]
5,Justice League,"November 17, 2017","$661,326,987",$300 million,DC,39% (411 reviews)[591]
6,Aquaman,"December 21, 2018","$1,152,028,393",$160 million,DC,65% (414 reviews)[594]
7,Shazam!,"April 5, 2019","$367,799,011",$100 million,DC,90% (421 reviews)[597]
8,Birds of Prey,"February 7, 2020","$205,372,791",$82 million,DC,78% (445 reviews)[601]
9,Wonder Woman 1984,"December 25, 2020","$169,601,036",$200 million,DC,58% (455 reviews)[603]
10,The Suicide Squad,"August 6, 2021","$168,717,425",$185 million,DC,90% (386 reviews)[607]
11,Black Adam,"October 21, 2022","$393,452,111",$190 million,DC,39% (307 reviews)[609]
12,Shazam! Fury of the Gods,"March 17, 2023","$134,138,006",$125 million,DC,49% (263 reviews)[612]
13,The Flash,"June 16, 2023","$271,433,313",$200 million,DC,63% (390 reviews)[614]
14,Blue Beetle,"August 18, 2023","$130,788,072",$104 million,DC,77% (277 reviews)[617]
15,Aquaman and the Lost Kingdom,"December 22, 2023","$439,381,226",$205 million,DC,33% (213 reviews)[620]
16,Superman,"July 11, 2025","$612,263.305",$225 million,DC,83% (484 reviews)[240]

In [ ]:
Movies_clean = pd.concat([M_Clean, DCMovies1], ignore_index=True)
Movies_clean.index = Movies_clean.index + 1
Movies_clean

,Movie,Release_Date,Budget,Box_Office,Franchise,Rotten_Tomatoes
1,Iron Man,"May 2, 2008",$140 million,"$585,796,247",Marvel,94% (282 reviews)[329]
2,The Incredible Hulk,"June 13, 2008",$137.5–150 million,"$264,770,996",Marvel,68% (237 reviews)[332]
3,Iron Man 2,"May 7, 2010",$170–200 million,"$623,933,331",Marvel,72% (305 reviews)[335]
4,Thor,"May 6, 2011",$150 million,"$449,326,618",Marvel,77% (296 reviews)[338]
5,Captain America: The First Avenger,"July 22, 2011",$140 million,"$370,569,774",Marvel,80% (276 reviews)[341]
6,The Avengers,"May 4, 2012",$220 million,"$1,520,538,536",Marvel,91% (368 reviews)[344]
7,Iron Man 3,"May 3, 2013",$200 million,"$1,215,577,205",Marvel,79% (331 reviews)[347]
8,Thor: The Dark World,"November 8, 2013",$150–170 million,"$644,783,140",Marvel,67% (290 reviews)[350]
9,Captain America: The Winter Soldier,"April 4, 2014",$170–177 million,"$714,421,503",Marvel,90% (311 reviews)[352]
10,Guardians of the Galaxy,"August 1, 2014",$170 million,"$773,350,147",Marvel,92% (336 reviews)[355]
11,Avengers: Age of Ultron,"May 1, 2015",$250–444 million,"$1,405,018,048",Marvel,75% (372 reviews)[359]
12,Ant-Man,"July 17, 2015",$130 million,"$519,311,965",Marvel,83% (341 reviews)[361]
13,Captain America: Civil War,"May 6, 2016",$250 million,"$1,155,046,416",Marvel,90% (431 reviews)[364]
14,Doctor Strange,"November 4, 2016",$165 million,"$677,796,076",Marvel,89% (389 reviews)[366]
15,Guardians of the Galaxy Vol. 2,"May 5, 2017",$200 million,"$863,756,051",Marvel,85% (425 reviews)[369]
16,Spider-Man: Homecoming,"July 7, 2017",$175 million,"$880,166,924",Marvel,92% (400 reviews)[371]
17,Thor: Ragnarok,"November 3, 2017",$180 million,"$855,301,806",Marvel,93% (439 reviews)[374]
18,Black Panther,"February 16, 2018",$200 million,"$1,374,959,729",Marvel,96% (532 reviews)[376]
19,Avengers: Infinity War,"April 27, 2018",$325–400 million,"$2,052,415,039",Marvel,85% (492 reviews)[379]
20,Ant-Man and the Wasp,"July 6, 2018",$162 million,"$622,674,139",Marvel,87% (446 reviews)[383]
21,Captain Marvel,"March 8, 2019",$150–175 million,"$1,131,416,446",Marvel,79% (552 reviews)[385]
22,Avengers: Endgame,"April 26, 2019",$356–400 million,"$2,799,439,100",Marvel,94% (551 reviews)[388]
23,Spider-Man: Far From Home,"July 2, 2019",$160 million,"$1,138,121,790",Marvel,91% (455 reviews)[391]
24,Black Widow,"July 9, 2021",$200 million,"$379,751,655[e]",Marvel,79% (462 reviews)[394]
25,Shang-Chi and the Legend of the Ten Rings,"September 3, 2021",$150–200 million,"$432,243,292",Marvel,92% (343 reviews)[397]
26,Eternals,"November 5, 2021",$236.2 million,"$402,064,899",Marvel,47% (417 reviews)[400]
27,Spider-Man: No Way Home,"December 17, 2021",$200 million,"$1,928,040,905",Marvel,93% (432 reviews)[403]
28,Doctor Strange in the Multiverse of Madness,"May 6, 2022",$172–200 million,"$955,775,804",Marvel,73% (466 reviews)[406]
29,Thor: Love and Thunder,"July 8, 2022",$250 million,"$760,928,081",Marvel,63% (449 reviews)[409]
30,Black Panther: Wakanda Forever,"November 11, 2022",$250 million,"$859,208,836",Marvel,84% (450 reviews)[412]
31,Ant-Man and the Wasp: Quantumania,"February 17, 2023",$388.4 million,"$476,071,180",Marvel,46% (412 reviews)[415]
32,Guardians of the Galaxy Vol. 3,"May 5, 2023",$250 million,"$845,555,777",Marvel,82% (407 reviews)[418]
33,The Marvels,"November 10, 2023",$375 million,"$206,136,825",Marvel,62% (370 reviews)[421]
34,Deadpool & Wolverine,"July 26, 2024",$200 million,"$1,338,073,645",Marvel,78% (413 reviews)[424]
35,Captain America: Brave New World,"February 14, 2025",$180 million,"$415,101,577",Marvel,46% (365 reviews)[427]
36,Thunderbolts*,"May 2, 2025",$180 million,"$382,436,917",Marvel,88% (354 reviews)[430]
37,The Fantastic Four: First Steps,"July 25, 2025",$200 million,"$511,526,150",Marvel,87% (388 reviews)[433]
38,Man of Steel,"June 14, 2013",$225 million,"$670,145,518",DC,57% (340 reviews)[578]
39,Batman v Superman: Dawn of Justice,"March 25, 2016",$250 million,"$874,362,803",DC,29% (439 reviews)[581]
40,Suicide Squad,"August 5, 2016",$175 million,"$749,200,054",DC,26% (394 reviews)[584]
41,Wonder Woman,"June 2, 2017",$149 million,"$823,970,682",DC,93% (480 reviews)[587]
42,Justice League,"November 17, 2017",$300 million,"$661,326,987",DC,39% (411 reviews)[591]
43,Aquaman,"December 21, 2018",$160 million,"$1,152,028,393",DC,65% (414 reviews)[594]
44,Shazam!,"April 5, 2019",$100 million,"$367,799,011",DC,90% (421 reviews)[597]
45,Birds of Prey,"February 7, 2020",$82 million,"$205,372,791",DC,78% (445 reviews)[601]
46,Wonder Woman 1984,"December 25, 2020",$200 million,"$169,601,036",DC,58% (455 reviews)[603]
47,The Suicide Squad,"August 6, 2021",$185 million,"$168,717,425",DC,90% (386 reviews)[607]
48,Black Adam,"October 21, 2022",$190 million,"$393,452,111",DC,39% (307 reviews)[609]
49,Shazam! Fury of the Gods,"March 17, 2023",$125 million,"$134,138,006",DC,49% (263 reviews)[612]
50,The Flash,"June 16, 2023",$200 million,"$271,433,313",DC,63% (390 reviews)[614]
51,Blue Beetle,"August 18, 2023",$104 million,"$130,788,072",DC,77% (277 reviews)[617]
52,Aquaman and the Lost Kingdom,"December 22, 2023",$205 million,"$439,381,226",DC,33% (213 reviews)[620]
53,Superman,"July 11, 2025",$225 million,"$612,263.305",DC,83% (484 reviews)[240]

## Data Cleaning

In [ ]:
Movies_clean["Rotten_Tomatoes"] = Movies_clean["Rotten_Tomatoes"].str.extract(r"(\d+)").astype(int) # regexp

In [ ]:
Movies_clean

,Movie,Release_Date,Budget,Box_Office,Franchise,Rotten_Tomatoes
1,Iron Man,"May 2, 2008",$140 million,"$585,796,247",Marvel,94
2,The Incredible Hulk,"June 13, 2008",$137.5–150 million,"$264,770,996",Marvel,68
3,Iron Man 2,"May 7, 2010",$170–200 million,"$623,933,331",Marvel,72
4,Thor,"May 6, 2011",$150 million,"$449,326,618",Marvel,77
5,Captain America: The First Avenger,"July 22, 2011",$140 million,"$370,569,774",Marvel,80
6,The Avengers,"May 4, 2012",$220 million,"$1,520,538,536",Marvel,91
7,Iron Man 3,"May 3, 2013",$200 million,"$1,215,577,205",Marvel,79
8,Thor: The Dark World,"November 8, 2013",$150–170 million,"$644,783,140",Marvel,67
9,Captain America: The Winter Soldier,"April 4, 2014",$170–177 million,"$714,421,503",Marvel,90
10,Guardians of the Galaxy,"August 1, 2014",$170 million,"$773,350,147",Marvel,92
11,Avengers: Age of Ultron,"May 1, 2015",$250–444 million,"$1,405,018,048",Marvel,75
12,Ant-Man,"July 17, 2015",$130 million,"$519,311,965",Marvel,83
13,Captain America: Civil War,"May 6, 2016",$250 million,"$1,155,046,416",Marvel,90
14,Doctor Strange,"November 4, 2016",$165 million,"$677,796,076",Marvel,89
15,Guardians of the Galaxy Vol. 2,"May 5, 2017",$200 million,"$863,756,051",Marvel,85
16,Spider-Man: Homecoming,"July 7, 2017",$175 million,"$880,166,924",Marvel,92
17,Thor: Ragnarok,"November 3, 2017",$180 million,"$855,301,806",Marvel,93
18,Black Panther,"February 16, 2018",$200 million,"$1,374,959,729",Marvel,96
19,Avengers: Infinity War,"April 27, 2018",$325–400 million,"$2,052,415,039",Marvel,85
20,Ant-Man and the Wasp,"July 6, 2018",$162 million,"$622,674,139",Marvel,87
21,Captain Marvel,"March 8, 2019",$150–175 million,"$1,131,416,446",Marvel,79
22,Avengers: Endgame,"April 26, 2019",$356–400 million,"$2,799,439,100",Marvel,94
23,Spider-Man: Far From Home,"July 2, 2019",$160 million,"$1,138,121,790",Marvel,91
24,Black Widow,"July 9, 2021",$200 million,"$379,751,655[e]",Marvel,79
25,Shang-Chi and the Legend of the Ten Rings,"September 3, 2021",$150–200 million,"$432,243,292",Marvel,92
26,Eternals,"November 5, 2021",$236.2 million,"$402,064,899",Marvel,47
27,Spider-Man: No Way Home,"December 17, 2021",$200 million,"$1,928,040,905",Marvel,93
28,Doctor Strange in the Multiverse of Madness,"May 6, 2022",$172–200 million,"$955,775,804",Marvel,73
29,Thor: Love and Thunder,"July 8, 2022",$250 million,"$760,928,081",Marvel,63
30,Black Panther: Wakanda Forever,"November 11, 2022",$250 million,"$859,208,836",Marvel,84
31,Ant-Man and the Wasp: Quantumania,"February 17, 2023",$388.4 million,"$476,071,180",Marvel,46
32,Guardians of the Galaxy Vol. 3,"May 5, 2023",$250 million,"$845,555,777",Marvel,82
33,The Marvels,"November 10, 2023",$375 million,"$206,136,825",Marvel,62
34,Deadpool & Wolverine,"July 26, 2024",$200 million,"$1,338,073,645",Marvel,78
35,Captain America: Brave New World,"February 14, 2025",$180 million,"$415,101,577",Marvel,46
36,Thunderbolts*,"May 2, 2025",$180 million,"$382,436,917",Marvel,88
37,The Fantastic Four: First Steps,"July 25, 2025",$200 million,"$511,526,150",Marvel,87
38,Man of Steel,"June 14, 2013",$225 million,"$670,145,518",DC,57
39,Batman v Superman: Dawn of Justice,"March 25, 2016",$250 million,"$874,362,803",DC,29
40,Suicide Squad,"August 5, 2016",$175 million,"$749,200,054",DC,26
41,Wonder Woman,"June 2, 2017",$149 million,"$823,970,682",DC,93
42,Justice League,"November 17, 2017",$300 million,"$661,326,987",DC,39
43,Aquaman,"December 21, 2018",$160 million,"$1,152,028,393",DC,65
44,Shazam!,"April 5, 2019",$100 million,"$367,799,011",DC,90
45,Birds of Prey,"February 7, 2020",$82 million,"$205,372,791",DC,78
46,Wonder Woman 1984,"December 25, 2020",$200 million,"$169,601,036",DC,58
47,The Suicide Squad,"August 6, 2021",$185 million,"$168,717,425",DC,90
48,Black Adam,"October 21, 2022",$190 million,"$393,452,111",DC,39
49,Shazam! Fury of the Gods,"March 17, 2023",$125 million,"$134,138,006",DC,49
50,The Flash,"June 16, 2023",$200 million,"$271,433,313",DC,63
51,Blue Beetle,"August 18, 2023",$104 million,"$130,788,072",DC,77
52,Aquaman and the Lost Kingdom,"December 22, 2023",$205 million,"$439,381,226",DC,33
53,Superman,"July 11, 2025",$225 million,"$612,263.305",DC,83

In [ ]:
Movies_clean.duplicated().sum() # Checking for Duplicate dif any

np.int64(0)

In [ ]:
Movies_clean = Movies_clean.drop_duplicates()

In [ ]:
import re

def parse_budget(value):
    if pd.isna(value):
        return None
    # Remove $, commas, the word "million", and NBSP
    value = re.sub(r"[^\d\.\–-]", "", value)

    # If it's a range, take the average
    if "–" in value or "-" in value:
        sep = "–" if "–" in value else "-"
        parts = value.split(sep)
        nums = [float(p) for p in parts if p]
        return sum(nums) / len(nums) * 1_000_000
    else:
        return float(value) * 1_000_000

Movies_clean["Budget"] = Movies_clean["Budget"].apply(parse_budget)

In [ ]:
Movies_clean

,Movie,Release_Date,Budget,Box_Office,Franchise,Rotten_Tomatoes
1,Iron Man,"May 2, 2008","140,000,000","$585,796,247",Marvel,94
2,The Incredible Hulk,"June 13, 2008","143,750,000","$264,770,996",Marvel,68
3,Iron Man 2,"May 7, 2010","185,000,000","$623,933,331",Marvel,72
4,Thor,"May 6, 2011","150,000,000","$449,326,618",Marvel,77
5,Captain America: The First Avenger,"July 22, 2011","140,000,000","$370,569,774",Marvel,80
6,The Avengers,"May 4, 2012","220,000,000","$1,520,538,536",Marvel,91
7,Iron Man 3,"May 3, 2013","200,000,000","$1,215,577,205",Marvel,79
8,Thor: The Dark World,"November 8, 2013","160,000,000","$644,783,140",Marvel,67
9,Captain America: The Winter Soldier,"April 4, 2014","173,500,000","$714,421,503",Marvel,90
10,Guardians of the Galaxy,"August 1, 2014","170,000,000","$773,350,147",Marvel,92
11,Avengers: Age of Ultron,"May 1, 2015","347,000,000","$1,405,018,048",Marvel,75
12,Ant-Man,"July 17, 2015","130,000,000","$519,311,965",Marvel,83
13,Captain America: Civil War,"May 6, 2016","250,000,000","$1,155,046,416",Marvel,90
14,Doctor Strange,"November 4, 2016","165,000,000","$677,796,076",Marvel,89
15,Guardians of the Galaxy Vol. 2,"May 5, 2017","200,000,000","$863,756,051",Marvel,85
16,Spider-Man: Homecoming,"July 7, 2017","175,000,000","$880,166,924",Marvel,92
17,Thor: Ragnarok,"November 3, 2017","180,000,000","$855,301,806",Marvel,93
18,Black Panther,"February 16, 2018","200,000,000","$1,374,959,729",Marvel,96
19,Avengers: Infinity War,"April 27, 2018","362,500,000","$2,052,415,039",Marvel,85
20,Ant-Man and the Wasp,"July 6, 2018","162,000,000","$622,674,139",Marvel,87
21,Captain Marvel,"March 8, 2019","162,500,000","$1,131,416,446",Marvel,79
22,Avengers: Endgame,"April 26, 2019","378,000,000","$2,799,439,100",Marvel,94
23,Spider-Man: Far From Home,"July 2, 2019","160,000,000","$1,138,121,790",Marvel,91
24,Black Widow,"July 9, 2021","200,000,000","$379,751,655[e]",Marvel,79
25,Shang-Chi and the Legend of the Ten Rings,"September 3, 2021","175,000,000","$432,243,292",Marvel,92
26,Eternals,"November 5, 2021","236,200,000","$402,064,899",Marvel,47
27,Spider-Man: No Way Home,"December 17, 2021","200,000,000","$1,928,040,905",Marvel,93
28,Doctor Strange in the Multiverse of Madness,"May 6, 2022","186,000,000","$955,775,804",Marvel,73
29,Thor: Love and Thunder,"July 8, 2022","250,000,000","$760,928,081",Marvel,63
30,Black Panther: Wakanda Forever,"November 11, 2022","250,000,000","$859,208,836",Marvel,84
31,Ant-Man and the Wasp: Quantumania,"February 17, 2023","388,400,000","$476,071,180",Marvel,46
32,Guardians of the Galaxy Vol. 3,"May 5, 2023","250,000,000","$845,555,777",Marvel,82
33,The Marvels,"November 10, 2023","375,000,000","$206,136,825",Marvel,62
34,Deadpool & Wolverine,"July 26, 2024","200,000,000","$1,338,073,645",Marvel,78
35,Captain America: Brave New World,"February 14, 2025","180,000,000","$415,101,577",Marvel,46
36,Thunderbolts*,"May 2, 2025","180,000,000","$382,436,917",Marvel,88
37,The Fantastic Four: First Steps,"July 25, 2025","200,000,000","$511,526,150",Marvel,87
38,Man of Steel,"June 14, 2013","225,000,000","$670,145,518",DC,57
39,Batman v Superman: Dawn of Justice,"March 25, 2016","250,000,000","$874,362,803",DC,29
40,Suicide Squad,"August 5, 2016","175,000,000","$749,200,054",DC,26
41,Wonder Woman,"June 2, 2017","149,000,000","$823,970,682",DC,93
42,Justice League,"November 17, 2017","300,000,000","$661,326,987",DC,39
43,Aquaman,"December 21, 2018","160,000,000","$1,152,028,393",DC,65
44,Shazam!,"April 5, 2019","100,000,000","$367,799,011",DC,90
45,Birds of Prey,"February 7, 2020","82,000,000","$205,372,791",DC,78
46,Wonder Woman 1984,"December 25, 2020","200,000,000","$169,601,036",DC,58
47,The Suicide Squad,"August 6, 2021","185,000,000","$168,717,425",DC,90
48,Black Adam,"October 21, 2022","190,000,000","$393,452,111",DC,39
49,Shazam! Fury of the Gods,"March 17, 2023","125,000,000","$134,138,006",DC,49
50,The Flash,"June 16, 2023","200,000,000","$271,433,313",DC,63
51,Blue Beetle,"August 18, 2023","104,000,000","$130,788,072",DC,77
52,Aquaman and the Lost Kingdom,"December 22, 2023","205,000,000","$439,381,226",DC,33
53,Superman,"July 11, 2025","225,000,000","$612,263.305",DC,83

In [ ]:
pd.set_option('display.float_format', '{:,.0f}'.format)

In [ ]:

def parse(x):
    if pd.isna(x):
        return None
    # Remove $, commas, the word "million", and NBSP
    x = re.sub(r'\[.*?\]', '', str(x))  # remove [ ... ]
    x = x.replace('$', '').replace(',', '').strip()
    return int(x) if x.isdigit() else int(float(x))

Movies_clean["Box_Office"] = Movies_clean["Box_Office"].apply(parse)

In [ ]:
Movies_clean

,Movie,Release_Date,Budget,Box_Office,Franchise,Rotten_Tomatoes
1,Iron Man,"May 2, 2008","140,000,000",585796247,Marvel,94
2,The Incredible Hulk,"June 13, 2008","143,750,000",264770996,Marvel,68
3,Iron Man 2,"May 7, 2010","185,000,000",623933331,Marvel,72
4,Thor,"May 6, 2011","150,000,000",449326618,Marvel,77
5,Captain America: The First Avenger,"July 22, 2011","140,000,000",370569774,Marvel,80
6,The Avengers,"May 4, 2012","220,000,000",1520538536,Marvel,91
7,Iron Man 3,"May 3, 2013","200,000,000",1215577205,Marvel,79
8,Thor: The Dark World,"November 8, 2013","160,000,000",644783140,Marvel,67
9,Captain America: The Winter Soldier,"April 4, 2014","173,500,000",714421503,Marvel,90
10,Guardians of the Galaxy,"August 1, 2014","170,000,000",773350147,Marvel,92
11,Avengers: Age of Ultron,"May 1, 2015","347,000,000",1405018048,Marvel,75
12,Ant-Man,"July 17, 2015","130,000,000",519311965,Marvel,83
13,Captain America: Civil War,"May 6, 2016","250,000,000",1155046416,Marvel,90
14,Doctor Strange,"November 4, 2016","165,000,000",677796076,Marvel,89
15,Guardians of the Galaxy Vol. 2,"May 5, 2017","200,000,000",863756051,Marvel,85
16,Spider-Man: Homecoming,"July 7, 2017","175,000,000",880166924,Marvel,92
17,Thor: Ragnarok,"November 3, 2017","180,000,000",855301806,Marvel,93
18,Black Panther,"February 16, 2018","200,000,000",1374959729,Marvel,96
19,Avengers: Infinity War,"April 27, 2018","362,500,000",2052415039,Marvel,85
20,Ant-Man and the Wasp,"July 6, 2018","162,000,000",622674139,Marvel,87
21,Captain Marvel,"March 8, 2019","162,500,000",1131416446,Marvel,79
22,Avengers: Endgame,"April 26, 2019","378,000,000",2799439100,Marvel,94
23,Spider-Man: Far From Home,"July 2, 2019","160,000,000",1138121790,Marvel,91
24,Black Widow,"July 9, 2021","200,000,000",379751655,Marvel,79
25,Shang-Chi and the Legend of the Ten Rings,"September 3, 2021","175,000,000",432243292,Marvel,92
26,Eternals,"November 5, 2021","236,200,000",402064899,Marvel,47
27,Spider-Man: No Way Home,"December 17, 2021","200,000,000",1928040905,Marvel,93
28,Doctor Strange in the Multiverse of Madness,"May 6, 2022","186,000,000",955775804,Marvel,73
29,Thor: Love and Thunder,"July 8, 2022","250,000,000",760928081,Marvel,63
30,Black Panther: Wakanda Forever,"November 11, 2022","250,000,000",859208836,Marvel,84
31,Ant-Man and the Wasp: Quantumania,"February 17, 2023","388,400,000",476071180,Marvel,46
32,Guardians of the Galaxy Vol. 3,"May 5, 2023","250,000,000",845555777,Marvel,82
33,The Marvels,"November 10, 2023","375,000,000",206136825,Marvel,62
34,Deadpool & Wolverine,"July 26, 2024","200,000,000",1338073645,Marvel,78
35,Captain America: Brave New World,"February 14, 2025","180,000,000",415101577,Marvel,46
36,Thunderbolts*,"May 2, 2025","180,000,000",382436917,Marvel,88
37,The Fantastic Four: First Steps,"July 25, 2025","200,000,000",511526150,Marvel,87
38,Man of Steel,"June 14, 2013","225,000,000",670145518,DC,57
39,Batman v Superman: Dawn of Justice,"March 25, 2016","250,000,000",874362803,DC,29
40,Suicide Squad,"August 5, 2016","175,000,000",749200054,DC,26
41,Wonder Woman,"June 2, 2017","149,000,000",823970682,DC,93
42,Justice League,"November 17, 2017","300,000,000",661326987,DC,39
43,Aquaman,"December 21, 2018","160,000,000",1152028393,DC,65
44,Shazam!,"April 5, 2019","100,000,000",367799011,DC,90
45,Birds of Prey,"February 7, 2020","82,000,000",205372791,DC,78
46,Wonder Woman 1984,"December 25, 2020","200,000,000",169601036,DC,58
47,The Suicide Squad,"August 6, 2021","185,000,000",168717425,DC,90
48,Black Adam,"October 21, 2022","190,000,000",393452111,DC,39
49,Shazam! Fury of the Gods,"March 17, 2023","125,000,000",134138006,DC,49
50,The Flash,"June 16, 2023","200,000,000",271433313,DC,63
51,Blue Beetle,"August 18, 2023","104,000,000",130788072,DC,77
52,Aquaman and the Lost Kingdom,"December 22, 2023","205,000,000",439381226,DC,33
53,Superman,"July 11, 2025","225,000,000",612263,DC,83

In [ ]:
Movies_clean.to_excel("Movies_clean.xlsx", index=False)